-- Copyright (c) Microsoft Corporation.
-- Licensed under the MIT License.

CREATE TABLE [Persisted].[Transaction] 
( 
TransactionKey										INT					NOT NULL,
TransactionChangeHash								BINARY(32)			NOT NULL,
MsnfpAdjustmentComment								NVARCHAR(500)			NULL,
MsnfpAdjustmentReason								NVARCHAR(500)			NULL,
MsnfpAdjustmentReasonDisplay						NVARCHAR(500)			NULL,
MsnfpAdjustmentType									NVARCHAR(500)			NULL,
MsnfpAdjustmentTypeDisplay							NVARCHAR(500)			NULL,
MsnfpAmount											DECIMAL(18,4)			NULL,
MsnfpAmountBase										DECIMAL(18,4)			NULL,
MsnfpAnonymity										NVARCHAR(500)			NULL,
MsnfpAnonymityDisplay								NVARCHAR(500)			NULL,
MsnfpBookdate										DATETIME2(7)			NULL,
CreatedBy											NVARCHAR(500)			NULL,
CreatedOnBehalfBy									NVARCHAR(500)			NULL,
CreatedOn											DATETIME2(7)			NULL,
TransactionCurrencyId								NVARCHAR(500)			NULL,
MsiatiCurrencyValuedate								DATETIME2(7)			NULL,
MsnfpDataEntryReference								NVARCHAR(500)			NULL,
MsnfpDataEntrySource								NVARCHAR(500)			NULL,
MsnfpDataEntrySourceDisplay							NVARCHAR(500)			NULL,
MsiatiDescription									NVARCHAR(500)			NULL,
MsiatiDisbursementchannelid							NVARCHAR(500)			NULL,
MsnfpEffectiveCampaignId							NVARCHAR(500)			NULL,
MsnfpEffectiveSourceCode							NVARCHAR(500)			NULL,
ExchangeRate										DECIMAL(18,4)			NULL,
MsnfpExchangeRateDate								DATETIME2(7)			NULL,
MsiatiFinanceTypeId									NVARCHAR(500)			NULL,
MsiatiFlowTypeId									NVARCHAR(500)			NULL,
MsiatiHumanitarian									BIT						NULL,
ImportSequenceNumber								INT						NULL,
MsnfpIsAdjusted										BIT						NULL,
ModifiedBy											NVARCHAR(500)			NULL,
ModifiedOnBehalfBy									NVARCHAR(500)			NULL,
ModifiedOn											DATETIME2(7)			NULL,
MsnfpName											NVARCHAR(500)			NULL,
MsnfpOriginalTxnAdjustedId							NVARCHAR(500)			NULL,
MsnfpOriginatingCampaignId							NVARCHAR(500)			NULL,
MsnfpOriginatingSourceCode							NVARCHAR(500)			NULL,
OwnerId												NVARCHAR(500)			NULL,
OwningBusinessUnit									NVARCHAR(500)			NULL,
OwningTeam											NVARCHAR(500)			NULL,
OwningUser											NVARCHAR(500)			NULL,
MsnfpTransactionPaymentMethodId						NVARCHAR(500)			NULL,
MsnfpTransactionPaymentScheduleid					NVARCHAR(500)			NULL,
MsnfpPostedDate										DATETIME2(7)			NULL,
MsiatiProviderActivityIdentifier					NVARCHAR(500)			NULL,
MsiatiProviderOrganizationId						NVARCHAR(500)			NULL,
MsnfpTransactionReceiptonAccountId					NVARCHAR(500)			NULL,
MsnfpReceivedDate									DATETIME2(7)			NULL,
MsiatiRecipientActivityidentifier					NVARCHAR(500)			NULL,
MsiatiRecipientCountryId							NVARCHAR(500)			NULL,
MsiatiRecipientCountryDescription					NVARCHAR(500)			NULL,
MsiatiRecipientOrganizationId						NVARCHAR(500)			NULL,
MsiatiRecipientRegionId								NVARCHAR(500)			NULL,
MsiatiRecipientRegionDescription					NVARCHAR(500)			NULL,
OverriddenCreatedOn									DATETIME2(7)			NULL,
MsiatiReference										NVARCHAR(500)			NULL,
StateCode											NVARCHAR(500)			NULL,
StateCodeDisplay									NVARCHAR(500)			NULL,
StatusCode											NVARCHAR(500)			NULL,
StatusCodeDisplay									NVARCHAR(500)			NULL,
MsiatiTiedStatusId									NVARCHAR(500)			NULL,
TimeZoneRuleVersionNumber							INT						NULL,
MsnfpTransactionId									NVARCHAR(500)		NOT	NULL,
UtcConversionTimeZoneCode							INT						NULL,
VersionNumber										BIGINT					NULL,
InsertedDate										DATETIME2(7)		NOT NULL
)
WITH
(
    DISTRIBUTION = ROUND_ROBIN,
    CLUSTERED COLUMNSTORE INDEX
)
