-- Copyright (c) Microsoft Corporation.
-- Licensed under the MIT License.

CREATE TABLE [Persisted].[Campaign] 
(  	CampaignKey									INT				NOT NULL,
	CampaignChangeHash							BINARY(32)		NOT NULL,
	StageId										NVARCHAR(500)		NULL,
	TraversedPath								NVARCHAR(500)		NULL,
	MsnfpAquisitionSource						NVARCHAR(500)		NULL,
    ActualEnd									DATETIME2(7)		NULL,											
    ActualStart									DATETIME2(7)		NULL,		
	MsnfpAppealSegment							BIGINT				NULL,
    MsnfpAppealSegmentDisplay					NVARCHAR(500)		NULL,
    BudgetedCost								DECIMAL(18,4)		NULL,
    BudgetedCostBase							DECIMAL(18,4)		NULL,
    CampaignId									NVARCHAR(500)	NOT	NULL,
	MsnfpCampaignCategory						BIGINT				NULL,
    MsnfpCampaignCategoryDisplay				NVARCHAR(500)		NULL,
    CodeName									NVARCHAR(500)		NULL,
	MsnfpCampaignType							BIGINT				NULL,
    MsnfpCampaignTypeDisplay					NVARCHAR(500)		NULL,
	TypeCode									BIGINT				NULL,
    TypeCodeDisplay								NVARCHAR(500)		NULL,
	MsnfpChannel								BIGINT				NULL,
    MsnfpChannelDisplay							NVARCHAR(500)		NULL,
    CreatedBy									NVARCHAR(500)		NULL,
    CreatedOnBehalfBy							NVARCHAR(500)		NULL,
	CreatedOn									DATETIME2(7)		NULL,
    TransactionCurrencyId						NVARCHAR(500)		NULL,
	MsnfpCampaignDefaultDesignation				NVARCHAR(500)		NULL,
    Description									NVARCHAR(500)		NULL,
    MsnfpEffort									BIGINT				NULL,
    MsnfpEffortDisplay							NVARCHAR(500)		NULL,
    EmailAddress								NVARCHAR(500)		NULL,
	EntityImage									NVARCHAR(500)		NULL,
    EntityImageTimestamp						BIGINT				NULL,
    EntityImageUrl								NVARCHAR(500)		NULL,
	EntityImageId								NVARCHAR(500)		NULL,
	ExpectedRevenue								DECIMAL(18,4)		NULL,
    ExpectedRevenueBase							DECIMAL(18,4)		NULL,
    ExchangeRate								DECIMAL(18,4)		NULL,
    ExpectedResponse							BIGINT				NULL,
	MsnfpFirstResponseDate						DATETIME2(7)		NULL,
	ImportSequenceNumber						BIGINT				NULL,
    MsnfpLastResponseDate						DATETIME2(7)		NULL,
    Message										NVARCHAR(500)		NULL,
    OtherCost									DECIMAL(18,4)		NULL,
    OtherCostBase								DECIMAL(18,4)		NULL,
    ModifiedBy									NVARCHAR(500)		NULL,
    ModifiedOnBehalfBy							NVARCHAR(500)		NULL,
    ModifiedOn									DATETIME2(7)		NULL,
	Name										NVARCHAR(500)		NULL,
    Objective									NVARCHAR(500)		NULL,
	OwnerId										NVARCHAR(500)		NULL,
    OwningBusinessUnit							NVARCHAR(500)		NULL,
    OwningTeam									NVARCHAR(500)		NULL,
    OwningUser									NVARCHAR(500)		NULL,
    PricelistId									NVARCHAR(500)		NULL,
    ProcessId									NVARCHAR(500)		NULL,
    PromotionCodeName							NVARCHAR(500)		NULL,
    ProposedEnd									DATETIME2(7)		NULL,
    ProposedStart								DATETIME2(7)		NULL,
    OverriddenCreatedOn							DATETIME2(7)		NULL,
    MsnfpSourceCode								NVARCHAR(500)		NULL,
    MsnfpStartDate								DATETIME2(7)		NULL,
	StateCode									BIGINT				NULL,
    StateCodeDisplay							NVARCHAR(500)		NULL,
    StatusCode									BIGINT				NULL,
    StatusCodeDisplay							NVARCHAR(500)		NULL,
    MsnfpSubchannel								BIGINT				NULL,
    MsnfpSubchannelDisplay						NVARCHAR(500)		NULL,
    IsTemplate									BIT					NULL,
    TimezoneRuleVersionNumber					BIGINT				NULL,
    TmpRegardingObjectId						NVARCHAR(500)		NULL,
    TotalActualCost								DECIMAL(18,4)		NULL,
    TotalActualCostBase							DECIMAL(18,4)		NULL,
    TotalCampaignActivityActualCost				DECIMAL(18,4)		NULL,
    TotalCampaignActivityActualCostBase			DECIMAL(18,4)		NULL,
    UtcConversionTimezoneCode					BIGINT				NULL,
    VersionNumber								BIGINT				NULL,
	InsertedDate								DATETIME2(7)	NOT NULL
)
WITH
(
DISTRIBUTION = ROUND_ROBIN,
CLUSTERED COLUMNSTORE INDEX
)