SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Must be executed inside the target database
-- Views

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_FullDocument' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_FullDocument;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentsentimentscores' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentsentimentscores;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentkeyphrases' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentkeyphrases;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_fulldocumenttopics' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_fulldocumenttopics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documenttopicimages' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documenttopicimages;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentcompressedentities' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentcompressedentities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_fullentities' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_fullentities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_entityrankings' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_entityrankings;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documents' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documents;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_date' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_date;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_configuration' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_configuration;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_topickeyphrases' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_topickeyphrases;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentsearchterms' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentsearchterms;


-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentingestedtimes' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documentingestedtimes;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentsentimentscores' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documentsentimentscores;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentkeyphrases' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documentkeyphrases;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documenttopics' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documenttopics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documenttopicimages' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documenttopicimages;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='entities' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.entities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documents' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documents;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentpublishedtimes' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.documentpublishedtimes;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='date' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.[date];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='configuration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.[configuration];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='topickeyphrases' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.[topickeyphrases];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentsearchterms' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.[documentsearchterms];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='entityinitialcount' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.entityinitialcount;

-- Staging tables here
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='stg_entities' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.stg_entities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='stg_documenttopics' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.stg_documenttopics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='stg_documenttopicimages' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.stg_documenttopicimages;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='stg_documentcompressedentities' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.stg_documentcompressedentities;

-- Bring-Your-Own Entities tables here
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='userdefinedentities' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.userdefinedentities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='userdefinedentitydefinitions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.userdefinedentitydefinitions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='typedisplayinformation' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.typedisplayinformation;

-- Stored procedures
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_get_replication_counts' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_get_replication_counts;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_get_prior_content' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_get_prior_content;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_clean_stage_tables' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_clean_stage_tables;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_mergedata' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_mergedata;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_write_document' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_write_document;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_create_topic_key_phrase' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_create_topic_key_phrase;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_get_pull_status' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_get_pull_status;

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='bpst_news')
BEGIN
    EXEC ('CREATE SCHEMA bpst_news AUTHORIZATION dbo'); -- Avoid batch error
END;
