declare namespace NodeJS {
	interface ProcessEnv {
		APPLICATIONINSIGHTS_CONNECTION_STRING?: string;
		APPLICATIONINSIGHTS_ENDPOINT_URL?: string;
		APPLICATIONINSIGHTS_INSTRUMENTATION_KEY?: string;
		WORKLOAD_NAME?: string;
		DEFAULT_ITEM_NAME?: string;
		DEV_WORKSPACE_ID?: string;
		TELEMETRY_DISABLED?: string;
		WORKSPACE_MOVE_SIMULATION_WORKSPACE_IDS?: string;
	}
}
