<#
.SYNOPSIS
  Syncs fallback.ts from the English Content Snippets in .powerpages-site.

.DESCRIPTION
  Reads all MSVE_SPA Content Snippet .value.html files (en-US) and regenerates
  Portal-EDM/src/i18n/fallback.ts to match, keeping the dev fallback in sync
  with the Dataverse source of truth.

.EXAMPLE
    .\sync-strings.ps1
#>

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) -Parent
$snippetsDir = Join-Path $repoRoot "Portal-EDM/.powerpages-site/content-snippets"
$fallbackPath = Join-Path $repoRoot "Portal-EDM/src/i18n/fallback.ts"

# ── Collect all English MSVE_SPA snippet values ───────────────────────
$entries = [System.Collections.Generic.SortedDictionary[string,string]]::new()

$dirs = Get-ChildItem $snippetsDir -Directory -Filter "msve_spa-*"
foreach ($dir in $dirs) {
    $enDir = Join-Path $dir.FullName "en-US"
    if (-not (Test-Path $enDir)) { continue }

    $yml = Get-ChildItem $enDir -Filter "*.contentsnippet.yml" | Select-Object -First 1
    $val = Get-ChildItem $enDir -Filter "*.contentsnippet.value.html" | Select-Object -First 1

    if (-not $yml -or -not $val) { continue }

    # Extract snippet name from yml
    $ymlContent = Get-Content $yml.FullName -Raw -Encoding utf8
    $nameMatch = [regex]::Match($ymlContent, 'name:\s*(.+)')
    if (-not $nameMatch.Success) { continue }
    $name = $nameMatch.Groups[1].Value.Trim()

    # Read value
    $value = [System.IO.File]::ReadAllText($val.FullName, [System.Text.UTF8Encoding]::new($false)).Trim()

    $entries[$name] = $value
}

if ($entries.Count -eq 0) {
    Write-Error "No MSVE_SPA snippets found. Run generate-snippets.ps1 first."
    return
}

Write-Host "Found $($entries.Count) snippet values" -ForegroundColor Cyan

# ── Group entries by category ─────────────────────────────────────────
$categories = [ordered]@{}
foreach ($key in $entries.Keys) {
    # MSVE_SPA/Common/Save → Common
    $parts = $key.Split('/')
    $cat = if ($parts.Length -ge 2) { $parts[1] } else { "Other" }
    if (-not $categories.Contains($cat)) {
        $categories[$cat] = [System.Collections.Generic.List[string]]::new()
    }
    $categories[$cat].Add($key)
}

# ── Category display names ────────────────────────────────────────────
$categoryLabels = @{
    'Common'         = 'Common / shared'
    'Nav'            = 'Navigation'
    'Status'         = 'Status badges'
    'Location'       = 'Location types'
    'Auth'           = 'Auth'
    'Filter'         = 'Filter sidebar'
    'Home'           = 'Home page'
    'Search'         = 'Search page'
    'Engagement'     = 'Engagement details'
    'MyEngagements'  = 'My Engagements'
    'Profile'        = 'Profile'
    'Day'            = 'Days of week'
    'AccessDenied'   = 'Access Denied'
    'NotFound'       = 'Not Found'
    'Success'        = 'Success'
    'Error'          = 'Error messages'
}

# ── Generate fallback.ts ──────────────────────────────────────────────
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Canonical English strings for the Volunteer Engagement SPA.")
[void]$sb.AppendLine("// This file serves three purposes:")
[void]$sb.AppendLine("//   1. Fallback for local (Vite) development when window.__VE_STRINGS is absent")
[void]$sb.AppendLine("//   2. The definitive key list — every key used by t() must appear here")
[void]$sb.AppendLine("//   3. Template for translators: duplicate this file, translate values, import into Dataverse")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// AUTO-GENERATED by scripts/localization/sync-strings.ps1 from Content Snippets.")
[void]$sb.AppendLine("// Do not edit manually — update the Content Snippets and re-run the script.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("export const fallbackStrings: Record<string, string> = {")

$catIndex = 0
foreach ($cat in $categories.Keys) {
    $label = if ($categoryLabels.ContainsKey($cat)) { $categoryLabels[$cat] } else { $cat }
    if ($catIndex -gt 0) { [void]$sb.AppendLine("") }
    [void]$sb.AppendLine("`t// ── $label $(('─' * (60 - $label.Length)))")

    foreach ($key in $categories[$cat]) {
        $val = $entries[$key].Replace("'", "\'")
        [void]$sb.AppendLine("`t'$key': '$val',")
    }
    $catIndex++
}

[void]$sb.AppendLine("};")

[System.IO.File]::WriteAllText($fallbackPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $($entries.Count) keys to fallback.ts" -ForegroundColor Green
Write-Host "File: $fallbackPath" -ForegroundColor Gray
