
-- Copyright (c) Microsoft Corporation.
-- Licensed under the MIT License.

CREATE VIEW [Presentation].[PaymentMethod]
AS 
SELECT
	  [PaymentMethodKey]                               
	 ,[PaymentMethodChangeHash]						
	 ,[MsnfpComments]									
	 ,[MsnfpContactId]									
	 ,[CreatedBy]										
	 ,[CreatedOnBehalfBy]								
	 ,[CreatedOn]										
	 ,[ImportSequenceNumber]							
	 ,[MsnfpIsDefault]									
	 ,[MsnfpLastAuthenticationStatus]					
	 ,[MsnfpLastAuthenticationStatusDisplay]			
	 ,[MsnfpLastAuthenticationStatusDate]				
	 ,[MsnfpLastAuthenticationStatusDetail]			
	 ,[MsnfpLastAuthenticationStatusTechnicalDetail]	
	 ,[ModifiedBy]										
	 ,[ModifiedOnBehalfBy]								
	 ,[ModifiedOn]										
	 ,[MsnfpName]										
	 ,[OwnerId]										
	 ,[OwningBusinessUnit]								
	 ,[OwningTeam]										
	 ,[OwningUser]										
	 ,[MsnfpPaymentMethodId]							
	 ,[MsnfpPaymentScheduleId]							
	 ,[MsnfpPayorId]									
	 ,[OverriddenCreatedOn]							
	 ,[StateCode]										
	 ,[StateCodeDisplay]								
	 ,[StatusCode]										
	 ,[StatusCodeDisplay]								
	 ,[TimezoneRuleVersionNumber]						
	 ,[MsnfpTransactionId]								
	 ,[MsnfpType]										
	 ,[MsnfpTypeDisplay]								
	 ,[UtcConversionTimezoneCode]						
	 ,[VersionNumber]									
	 ,[InsertedDate]														
FROM [Persisted].[PaymentMethod]
